services:
  network-server:
    build:
      context: ./network-server
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 0
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
    labels:
      - "traefik.http.routers.mm-network-play-jkoz5a-11-websecure.middlewares=websocket@file"
